### ISSUE TITLE
Push notifications permissions unknown

### ISSUE THREAD

**Issue by jerelevine** [Swrve/swrve-ios-sdk#236]
https://github.com/Swrve/swrve-ios-sdk/blob/aaa89d977e1ef1a38e2a7ebfc539b51bd5ea3a2a/SwrveSDKCommon/Common/SwrvePermissions.m#L126-L128

There's a bug where when Push Notification Permissions are not determined, the SDK is returned "denied"

**Comment by jerelevine** [comment]
Additionally, it also seems like push notifications permissions status may not be persisted or sent to the server at all.

**Comment by Sergio-Mira** [comment]
Thanks @jerelevine. It looks like this change was introduced due to some pre iOS10+ uncertainty when combined with silent push (always gives a token without the dialog) in the 4.11.X releases.
On an upcoming hotfix we'll be properly reporting iOS10+ unknown as 'unknown'.

When are you not seeing the permissions being sent to the server? From our testing they are sent when available.

**Comment by jerelevine** [comment]
Hi Sergio, thanks for looking into this for me. It looks like the data is being sent to the server but the value isn't being persisted in NSUserDefaults as is with all the other permissions. That's not a problem for me, it just made me wonder whether it was making it's way to the server.

**Comment by Sergio-Mira** [comment]
Thanks for the detailed information again. We are now reporting iOS10+ devices as unknown in 4.11.4 that has just been released, let us know how it goes!

**Comment by jerelevine** [comment]
Great thanks!
